networks:
  front-tier:
  back-tier:
services:
  db:
    image: mariadb:11.8
    restart: unless-stopped
    user: ${USERID}:${GROUPID}
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - ./docker/data/db:/var/lib/mysql
  fpm:
    build:
      context: docker/fpm
      args:
        UID: ${USERID}
        GID: ${GROUPID}
    restart: unless-stopped
    networks:
      - back-tier
    volumes:
      - ./Lychee:/var/www/html/lychee
      - /etc/localtime:/etc/localtime:ro
  web:
    build:
      context: docker/nginx
      args:
        UID: ${USERID}
        GID: ${GROUPID}
    restart: unless-stopped
    networks:
      - back-tier
      - front-tier
    ports:
      - "${WEB_PORT}:80"
    links:
      - fpm
    volumes:
      - ./Lychee/public:/var/www/html/lychee/public
  node:
    image: node:22-alpine
    volumes:
      - ./Lychee:/app
    working_dir: /app
    command: ["/bin/true"]
